# Generated by Django 5.1.4 on 2025-08-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hungerr', '0002_food_foodimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='user',
        ),
    ]
