import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Try to load initial from localStorage, default 'en'
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      return (localStorage.getItem('appLang') as Language) || 'en';
    } catch {
      return 'en';
    }
  });

  const setGoogleTranslateCookie = (lang: string) => {
    // the cookie format is /en/{targetLang} or /en/en. For 'en' it turns it off.
    // Setting both domain and non-domain cookies handles edge cases
    const val = lang === 'en' ? '/en/en' : `/en/${lang}`;
    document.cookie = `googtrans=${val}; path=/`;
    document.cookie = `googtrans=${val}; path=/; domain=${window.location.hostname}`;
  };

  const triggerGoogleTranslate = (lang: string) => {
    try {
      // Find the select element generated by Google Translate
      const gCombo = document.querySelector('.goog-te-combo') as HTMLSelectElement;
      if (gCombo) {
        gCombo.value = lang;
        // Google Translate listens for explicit 'change' events
        gCombo.dispatchEvent(new Event('change', { bubbles: true }));
      }
    } catch (e) {
      console.warn("Failed to trigger google translate widget manually. Relying on cookie+reload.");
    }
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('appLang', lang);
    setGoogleTranslateCookie(lang);
    
    // First try the seamless change
    triggerGoogleTranslate(lang);
    
    // Then reload completely to ensure dynamic components also get re-translated immediately
    // or if the seamlessly trigger failed
    setTimeout(() => {
      window.location.reload();
    }, 100);
  };

  useEffect(() => {
    document.documentElement.lang = language;
    setGoogleTranslateCookie(language);
    
    // This runs on mount/hydration incase google script loaded after us
    const timer = setTimeout(() => {
        if(language !== 'en') {
            triggerGoogleTranslate(language);
        }
    }, 1500);
    
    return () => clearTimeout(timer);
  }, [language]);

  // Compatibility function for legacy mapped text 
  const t = (key: string): string => {
    const mappings: Record<string, string> = {
      'nav.home': 'Home',
      'nav.map': 'Map',
      'nav.coinSystem': 'Coin System',
      'nav.contribute': 'Contribute',
      'nav.rteEnrollment': 'RTE Enrollment',
      'nav.marketplace': 'Marketplace',
      'hero.title': 'Fighting Hunger, Reducing Waste',
      'hero.subtitle': 'Connect surplus food with those in need through our intelligent platform',
      'hero.cta': 'Join the Movement',
      'stats.food_saved': 'Meals Saved',
      'stats.users': 'Active Users',
      'stats.locations': 'Partner Locations',
      'features.map.title': 'Interactive Food Map',
      'features.map.desc': 'Find nearby food sources and donation points',
      'features.ai.title': 'AI-Powered Matching',
      'features.ai.desc': 'Smart algorithms connect food with need',
      'features.community.title': 'Community Driven',
      'features.community.desc': 'Local volunteers and organizations working together',
      'contribute.title': 'Share Food, Share Hope',
      'contribute.desc': 'Your contribution can make a difference',
      'footer.mission': 'Building a world without hunger and food waste'
    };
    
    return mappings[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}